<?php

/**
 * @file
 * Primary module hooks for Localgov Sa11y module.
 */

/**
 * Implements hook_page_attachments().
 */
function localgov_sa11y_page_attachments(array &$page) {
  $admin_theme = \Drupal::config('system.theme')->get('admin');
  $active_theme = \Drupal::theme()->getActiveTheme()->getName();
  $using_admin_theme = $admin_theme === $active_theme;

  if (\Drupal::currentUser()->hasPermission('use_localgov_sa11y') && !$using_admin_theme) {
    $page['#attached']['library'][] = 'localgov_sa11y/localgov_sa11y';
  }

  $config = \Drupal::configFactory()->get('localgov_sa11y_options.settings');

  $page['#attached']['drupalSettings']['localgov_sa11y_options']['checkRoot'] = $config->get('checkRoot');
  $page['#attached']['drupalSettings']['localgov_sa11y_options']['containerIgnore'] = $config->get('containerIgnore');
  $page['#attached']['drupalSettings']['localgov_sa11y_options']['contrastIgnore'] = $config->get('contrastIgnore');
  $page['#attached']['drupalSettings']['localgov_sa11y_options']['linkIgnore'] = $config->get('linkIgnore');
  $page['#attached']['drupalSettings']['localgov_sa11y_options']['exportResultsPlugin'] = $config->get('exportResultsPlugin');
  $page['#attached']['drupalSettings']['localgov_sa11y_options']['checkAllHideToggles'] = $config->get('checkAllHideToggles');
  $page['#attached']['drupalSettings']['localgov_sa11y_options']['panelPosition'] = $config->get('panelPosition');
}
